### PR TITLE
Big refactor

### PR DESCRIPTION
**Pull request by emoon**
* Added proper Result type
* No unwrapping inside the open dialog functions. It now returns a correct restult type instead
* Added the nfd sources that is built using the gcc crate instead of having the user compile the code manually
* Added DialogBuilder to make it nicer to construct dialogs with filters and paths
* Added builder_open_jpg example which uses the builder code and only allows for opening of jpg files
* Fixed issue focus issue for Mac dialogs: Outlined here https://github.com/mlabbe/nativefiledialog/issues/7
* Support for multi open + example

### CODE REVIEW

**Comment by DenisKolodin** [comment]
@saurvs I like this one! I think we have to merge it.

@emoon Why didn't you attach `nativefiledialog` as a submodule?

**Comment by emoon** [comment]
I didn't use it as a submodule because I there were some fixes that hasn't been merged to the main repo that I wanted to get it. I guess I could have forked the main repro and used that one as I submodule but I opted to include the code instead as it would make it a bit easier to apply fixes for it if needed.

**Comment by DenisKolodin** [comment]
I can compile an original, but can't do it with a modified because of an error:

```cpp
nfd/src/nfd_win.cpp: In function 'nfdresult_t AddFiltersToDialog(IFileDialog*, const char*)':
nfd/src/nfd_win.cpp:204:19: error: invalid use of incomplete type 'IFileDialog {aka struct IFileDialog}'
     fileOpenDialog->SetFileTypes( filterCount+1, specList );
                   ^
In file included from nfd/src/nfd_win.cpp:17:0:
C:/msys64/mingw64/x86_64-w64-mingw32/include/ShObjIdl.h:672:19: note: forward declaration of 'IFileDialog {aka struct IFileDialog}'
 typedef interface IFileDialog IFileDialog;
                   ^
nfd/src/nfd_win.cpp: In function 'nfdresult_t SetDefaultPath(IFileDialog*, const char*)':
nfd/src/nfd_win.cpp:324:93: error: 'SHCreateItemFromParsingName' was not declared in this scope
     HRESULT result = SHCreateItemFromParsingName( defaultPathW, NULL, IID_PPV_ARGS(&folder) );
                                                                                             ^
nfd/src/nfd_win.cpp:341:11: error: invalid use of incomplete type 'IFileDialog {aka struct IFileDialog}'
     dialog->SetFolder( folder );
           ^
```

How can we fix it? Or what kind of changes have you done?

**Comment by emoon** [comment]
I removed the atlbase.h file (it wasn't needed for me and VS 2015 didn't find it) I compile it with VS 2015 community edition and also appveyor (auto-build) also compiles the code fine.

**Comment by emoon** [comment]
I haven't actually tried to compile with mingw no, only msvc so there might be that some extra flags are needed for that.

**Comment by DenisKolodin** [comment]
It looks like original lib compiles for GTK with mingw (no win version actually). But with your build script it's trying to compile win version. Which version we have to use for mingw? GTK probably...

**Comment by emoon** [comment]
I would assume that mingw on windows should use use the windows version. I guess this code here: https://github.com/emoon/nfd-rs/blob/refactor/build.rs#L37 needs to be changed so it can detect mingw as "windows"

**Comment by DenisKolodin** [comment]
Ok, I'll check it right now.

**Comment by emoon** [comment]
Thanks! It shouldn't be that hard to fix. Hopefully it's only another check that needs on that line.

**Comment by saurvs** [comment]
@emoon Everything looks good. I don't have a windows machine to test on so I can't offer any help for the compilation issue with mingw, and you should probably add in the appveyor config file you mentioned. Also you should add your name to the copyright in the license as well.

@DenisKolodin It's nearly a year since that Mac focus issue has been addressed, so I guess we can have use a patched local copy, and revert back with a submodule if the upstream repo gets fixed.

**Comment by DenisKolodin** [comment]
For mingw with cargo `TARGET` contains `windows` and win version was choosed.

The problem is deeper, `nativefiledialog` uses:

```python
# Cocoa OS X builds - clang
if target_os == 'darwin':
    nfd_files.append('nfd_cocoa.m')
    nfd_env.CC='clang -fcolor-diagnostics'

# Linux GTK+ 3 builds - GCC
elif target_os == 'posix':
    nfd_files.append('nfd_gtk.c')
    nfd_env.ParseConfig( 'pkg-config --cflags gtk+-3.0' )

# Windows builds - Visual Studio
elif target_os == 'win32':
nfd_files.append('nfd_win.cpp')
```

For mingw I actually have `msys` os, and it has never compiled correctly. Maybe it's impossible to compile with mingw at all. Trying...

**Comment by emoon** [comment]
@saurvs Thanks. I can add my name yes and I agree about the focus issue. Updates of the main repro seems slow which is another reason I opted for a local copy instead but as you say, we can switch to a submodule if we want

**Comment by DenisKolodin** [comment]
With GTK it compiles if I add:

```python
# Windows builds - MinGW
elif target_os == 'msys':
    nfd_files.append('nfd_gtk.c')
    nfd_env.ParseConfig( 'pkg-config --cflags gtk+-3.0' )
```

I'm trying to compile with 'nfd_win.cpp' under mingw...

**Comment by DenisKolodin** [comment]
https://github.com/mlabbe/nativefiledialog/pull/10 helps me a lot. I've fixed it. MinGW + Win compiles well!

@emoon I'll send you PR to your fork which fixes the problem. Could you merge it into this PR?

@saurvs `nativefiledialog` looks unmaintainable. We, really, have to patch it locally.

**Comment by emoon** [comment]
Sure I will merge it in.

**Comment by DenisKolodin** [comment]
MinGW support has implemented here: https://github.com/emoon/nfd-rs/pull/3

**Comment by DenisKolodin** [comment]
I've found that `nativefilesdialog` contains a lot of trailing spaces in sources. Will we have something to do with it?

**Comment by emoon** [comment]
No idea really. I guess it would be best to check if that is the case in the original repo also

**Comment by saurvs** [comment]
Shall I merge this in?

**Comment by DenisKolodin** [comment]
Yes, please! This PR grew too much. I use this and tested a lot: it's works fine!
Also, I'm creating AppVeyor builds test, but they aren't ready yet. I'll send it later as separated PR to won't grow this more.

**Comment by DenisKolodin** [comment]
Thank you!

**Comment by saurvs** [comment]
Sure!

**Pull request merged**
